### ISSUE TITLE
Add a social media preview

### ISSUE THREAD

**Issue by arbox** [yoshoku/rumale#10]
Hey!

I'm following your work on Rumale and would suggest, you'd better add the Logo to the social media preview which is newly available for project repositories. This ensures that links to Rumale's repository show the logo and not your avatar on Github.

To do so please go to "Settings->Social media preview" in this repository.

Thank you again for your work on this topic, it's very useful!

**Comment by yoshoku** [comment]
Thank you for your suggestion! I set the logo on social media view 👍
