### ISSUE TITLE
feature request: clustering metrics

### ISSUE THREAD

**Issue by Floghi** [yoshoku/rumale#14]
Hello,
first, congratz for this wonderfull project!
I'm using some of your clustering algorithms and I was wondering if you plan to add some basic metrics as the Silhouette Coefficient, the Calinski-Harabasz Index and the Davies-Bouldin Index. According to https://scikit-learn.org/stable/modules/clustering.html it will help in the chose of clusters number in a case of we have no clue on this number.

**Comment by yoshoku** [comment]
Thank you for your request. I will try to implement these evaluation measures 💪

**Comment by yoshoku** [comment]
@Floghi  I have implemented and released the [Silhouette Coefficient](https://yoshoku.github.io/rumale/doc/Rumale/EvaluationMeasure/SilhouetteScore.html), [Calinski-Harabasz Index](https://yoshoku.github.io/rumale/doc/Rumale/EvaluationMeasure/CalinskiHarabaszScore.html) and [Davies-Bouldin Index](https://yoshoku.github.io/rumale/doc/Rumale/EvaluationMeasure/DaviesBouldinScore.html) in version [0.13.7](https://rubygems.org/gems/rumale/versions/0.13.7).

```ruby
require 'rumale'

...

kmeans = Rumale::Clustering::KMeans.new(n_clusters: 2, random_seed: 1)
cluster_labels = kmeans.fit_predict(samples)

puts "Sh: #{Rumale::EvaluationMeasure::SilhouetteScore.new.score(samples, cluster_labels)}"
puts "CH: #{Rumale::EvaluationMeasure::CalinskiHarabaszScore.new.score(samples, cluster_labels)}"
puts "DB: #{Rumale::EvaluationMeasure::DaviesBouldinScore.new.score(samples, cluster_labels)}"
```

**Comment by yoshoku** [comment]
Thank you for your request. I will close this issue.

**Comment by Floghi** [comment]
Thanks, your work is really appreciated!
