### ISSUE TITLE
FP-Gowth algorithm

### ISSUE THREAD

**Issue by gabrielbaldao** [yoshoku/rumale#15]
Can I try add the algorithm of the association task, FP-Growth, in this repo?

**Comment by yoshoku** [comment]
Sorry.  I think that the frequent pattern mining (item set mining) algorithms are outside the scope of Rumale. Rumale intends to support classification, regression, clustering, and dimensionality reduction (matrix decomposition) as with scikit-learn. It is recommended to implement that as a new gem.
