### ISSUE TITLE
fit_bias: false is the default parameter for LinearRegression. Too difficult to find out ?

### ISSUE THREAD

**Issue by kojix2** [yoshoku/rumale#16]
Hello.

I have a question and a suggestion.
Do you want to change the default value of `fit_bias` to `true`?

In the `Rumale::LinearModel::LinearRegression` class, the default value of `fit_bias` is `false`.

In my understanding,  this means that the regression line will always go through (0, 0) unless you set `fit_bias: true`.

This is difficult for starters, I think.

If you're new to Rumale, you don't understand why the regression line doesn't work. They can't tell if Rumale is a buggy or missing an option until they search the document. Some people may quit before looking for documentation.

fit_intercept=True is the default value in sklearn. 
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

**Comment by yoshoku** [comment]
Thank you for your valuable proposal 👍 

I plan to improve the linear model estimators in `version 0.17.0`. At that time of that release, I would like to change the default value of the `fit_bias` parameter to `true`.
Moreover, the Elastic-net regression will be add in the next version 0.16.1. I will set the default value of that fit_bias parameter to true. 

Both versions will be released in this month.

**Comment by kojix2** [comment]
Thanks a lot!
