### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ankane** [yoshoku/rumale#17]
Hey @yoshoku, this library is great! Ruby could really use a comprehensive ML library.

It looks like the source code is well-commented, but I can't find online documentation for it. I think it would really help users if there was documentation similar to Scikit-learn ([linear regression example](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)). I had no idea how much you could with it until diving into the source code.

**Comment by yoshoku** [comment]
Thank you for your opinion. As you have pointed out, Rumale has only [API document](https://yoshoku.github.io/rumale/doc/). I know that problem. I am writing Rumale user guide little by little.

<img width="156" alt="contents" src="https://user-images.githubusercontent.com/5562409/72216930-fc110200-356a-11ea-9f80-78546ad36d80.png">

**Comment by ankane** [comment]
Thanks @yoshoku, I completely missed the docs badge in the readme. I think it'd be good to highlight it at the start of the usage section (or somewhere else in the readme). It could also be helpful to set it as the GitHub link instead of linking to the RubyGems page. Just suggestions, so no worries if you'd prefer not to change it.

A user guide would be amazing. I'm sure that's a lot of work. Happy to give feedback on it if it's helpful (either now or in the future).

**Comment by yoshoku** [comment]
Thank you for your suggestion 👍 
I have added documentation section to [README](https://github.com/yoshoku/rumale/blob/master/README.md) before usage section.

**Comment by ankane** [comment]
Perfect, thanks @yoshoku!
