### ISSUE TITLE
Example 1. XOR data - fails

### ISSUE THREAD

**Issue by lalusaud** [yoshoku/rumale#19]
I was testing rumale examples from https://yoshoku.github.io/rumale/doc/

The first example failed with this error - undefined local variable or method `x' for main:Object (NameError)

I replaced x with features and y with labels and it worked.

**Comment by yoshoku** [comment]
@lalusaud Thank you for your report. I have fixed mistake in the first example code on README (https://github.com/yoshoku/rumale/commit/a5d76a79bee5ec1872981df8897848d75b777fdd). The API documentation has also been updated. https://yoshoku.github.io/rumale/doc/

**Comment by lalusaud** [comment]
@yoshoku - Awesome! Thank you for fixing it quickly.
