### ISSUE TITLE
stack level too deep

### ISSUE THREAD

**Issue by hackhowtofaq** [yoshoku/rumale#28]
I am using Rumale::Ensemble::GradientBoostingRegressor.new with a 250MB csv file as training data, and I am getting

```
rumale/tree/gradient_tree_regressor.rb:117:in `apply': stack level too deep (SystemStackError)
```
during the fit

Bundler       2.2.11
Platforms   ruby, x86_64-linux

I tried to `ulimit -s unlimited`,
```
> ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 127649
max locked memory       (kbytes, -l) 65536
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

```

 but still no luck.

Thanks.

**Comment by yoshoku** [comment]
@hackhowtofaq It seems that the error occurred because a very deep tree was created. I recommend adjusting the parameters related to the depth of the tree.

```ruby
gbt = Rumale::Ensemble::GradientBoostingRegressor.new(max_depth: 10)
```

**Comment by hackhowtofaq** [comment]
@yoshoku 

I tried with `max_depth: 10` no luck again. Even with  `max_depth: 5`

**Comment by yoshoku** [comment]
@hackhowtofaq I could not reproduce this error in my environment and data. It is difficult for me to investigate this issue any further since I do not have the code and data that cause this error.

**Comment by hackhowtofaq** [comment]
I will try to produce it with dummy data and give you the minimum to reproduce.

**Comment by motine** [comment]
Had the same issue while using random forest. `max_depth` fixed it for me though.

**Comment by yoshoku** [comment]
I could not reproduce this error on the following  environment and data.

OS: macOS Big Sur 11.3
CPU: Apple M1
Memory: 16 GB
Console: iTerm2 (Rosetta)
Ruby: 2.5.8, 2.6.7, 2.7.3, and 3.0.1
Rumale: 0.23.0
Data set: LIBSVM DATA E2006-tfidf (485 MB)
https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/regression/E2006.train.bz2

Code:

```ruby
require 'numo/linalg/autoloader'
require 'parallel'
require 'rumale'

x, y = Rumale::Dataset.load_libsvm_file('E2006.train')

x_train, x_test, y_train, y_test = Rumale::ModelSelection.train_test_split(x, y, test_size: 0.2, random_seed: 1)

reg = Rumale::Ensemble::RandomForestRegressor.new(n_jobs: -1, random_seed: 1)

reg.fit(x_train, y_train)

p reg.apply(x_test).shape
```

**Comment by motine** [comment]
Turns out, I did get a `stack level too deep` after all. For me this happens when I call `predict` on a `Rumale::Ensemble::RandomForestClassifier`. Unfortunately, I can not share my data since it is personal data.

I have a suspicion though. I think [grow_node](https://github.com/yoshoku/rumale/blob/main/lib/rumale/tree/base_decision_tree.rb#L73) can return `nil` for a node which then gets added to the tree.

In [apply](https://github.com/yoshoku/rumale/blob/main/lib/rumale/tree/base_decision_tree.rb#L46) (and `apply_at_node`) we descend the tree. Yet, the case that a `left_leaf` _and_ `right_leaf` is not covered.

I have no idea if this suspicion is well-informed, but what do you think? Am I on to something?

**Comment by yoshoku** [comment]
I cannot investigate this phenomenon because it is difficult for me to reproduce that without the data in which the error occurred, the information of execution environment, and the stack trace at the time of the error.

**Comment by yoshoku** [comment]
It may be solved by giving a large value to `RUBY_THREAD_VM_STACK_SIZE`.

```ruby
$ irb
irb(main):001:0> RubyVM::DEFAULT_PARAMS[:thread_vm_stack_size]
=> 1048576
irb(main):002:0>

$ RUBY_THREAD_VM_STACK_SIZE=104857600 irb
irb(main):001:0> RubyVM::DEFAULT_PARAMS[:thread_vm_stack_size]
=> 104857600
irb(main):002:0>
```

**Comment by yoshoku** [comment]
I have developed a version that does not use recursive calls in the apply method. Please try this. If the error still occurs, it is difficult to determine the cause of the error without the input data and information about the execution environment.

Gemfile;

```ruby
gem 'rumale', git: 'git@github.com:yoshoku/rumale.git', branch: 'no_recursive_call'
```

or gem command:

```sh
$ gem install specific_install
$ gem specific_install git@github.com:yoshoku/rumale.git no_recursive_call
```

**Comment by motine** [comment]
Wow, thank you so much @yoshoku for the fast fix. I will try this out as soon as I can (unfortunately, another project is crazy right now). Thanks again and I will come back to you as soon as I can.

**Comment by hackhowtofaq** [comment]
I moved my project to https://github.com/ankane/xgboost

But I will try again with your fix.

Thanks

**Comment by yoshoku** [comment]
I have released a version that includes this fix (https://rubygems.org/gems/rumale/versions/0.23.1). If you encounter the same error, please report it. Thank you for your cooperation.
