### ISSUE TITLE
Online versions of algorithms

### ISSUE THREAD

**Issue by motine** [yoshoku/rumale#29]
first, thank you so much for providing this gem. It is awesome to have such an easy API to work with in Ruby.

I noticed that there are no incremental learning/online versions of the algorithms. For example, the `SGDClassifier` in sklearn, does support [partial_fit](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html#sklearn.linear_model.SGDClassifier.partial_fit). Are you planning on implementing something like this?

**Comment by yoshoku** [comment]
@motine Thank you for your interest. Currently, there are no plans to support online algorithms. However, it is an interesting idea, and I would like to consider the implementation of online algorithms as a future work.

**Comment by motine** [comment]
cool thanks for your answer.
