### ISSUE TITLE
Typo in project description

### ISSUE THREAD

**Issue by xyproto** [yoshoku/rumale#8]
Just a minor nitpick...

`Rumale is a machine learninig library in Ruby` should probably be `learning` instead of `learninig`.

Thanks for creating and sharing this project.

**Comment by yoshoku** [comment]
Thank you for your report 👍 👍 👍 I have fixed the typos. https://github.com/yoshoku/rumale/commit/5cfa89a90406640cf5c2ff6e8cc63e5e7de56e4d
